// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVeLzQedDzOhr5XOssahsZoU63av6A_c',
    appId: '1:768607843734:web:26a87e12c61338ca6219b7',
    messagingSenderId: '768607843734',
    projectId: 'loopage',
    authDomain: 'loopage.firebaseapp.com',
    storageBucket: 'loopage.firebasestorage.app',
    measurementId: 'G-MY9X4CP1HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWM8PM5v52F70z6P5R6Z2q6tEiyiq8lrU',
    appId: '1:768607843734:android:fbae3e652100e58a6219b7',
    messagingSenderId: '768607843734',
    projectId: 'loopage',
    storageBucket: 'loopage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPqFsDzgRGn0ItYlrhOF5grG5P-HoqjMk',
    appId: '1:768607843734:ios:b94f3417c2134e216219b7',
    messagingSenderId: '768607843734',
    projectId: 'loopage',
    storageBucket: 'loopage.firebasestorage.app',
    iosBundleId: 'com.loopage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPqFsDzgRGn0ItYlrhOF5grG5P-HoqjMk',
    appId: '1:768607843734:ios:bf827902b974804b6219b7',
    messagingSenderId: '768607843734',
    projectId: 'loopage',
    storageBucket: 'loopage.firebasestorage.app',
    iosBundleId: 'com.example.kodlingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZVeLzQedDzOhr5XOssahsZoU63av6A_c',
    appId: '1:768607843734:web:7f4a76aac935878c6219b7',
    messagingSenderId: '768607843734',
    projectId: 'loopage',
    authDomain: 'loopage.firebaseapp.com',
    storageBucket: 'loopage.firebasestorage.app',
    measurementId: 'G-ZRFKB0C67P',
  );
}
